--------------------------------------------------------------------------------
--
-- Created: Éamonn A. Duffy, 17-Apr-2019 (Wih the assistance of SSMS initially).
--
--------------------------------------------------------------------------------

USE [master]
GO

/****** Object:  Database [Css.V000]    Script Date: 17/04/2019 07:24:44 ******/
CREATE DATABASE [Css.V000]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Css.V000', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Css.V000.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Css.V000_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Css.V000_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Css.V000] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Css.V000].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Css.V000] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Css.V000] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Css.V000] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Css.V000] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Css.V000] SET ARITHABORT OFF 
GO

ALTER DATABASE [Css.V000] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Css.V000] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Css.V000] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Css.V000] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Css.V000] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Css.V000] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Css.V000] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Css.V000] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Css.V000] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Css.V000] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Css.V000] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Css.V000] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Css.V000] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Css.V000] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Css.V000] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Css.V000] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Css.V000] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Css.V000] SET RECOVERY FULL 
GO

ALTER DATABASE [Css.V000] SET  MULTI_USER 
GO

ALTER DATABASE [Css.V000] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Css.V000] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Css.V000] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Css.V000] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Css.V000] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Css.V000] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Css.V000] SET  READ_WRITE 
GO

